apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "stellar-node.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.size }}
  hostPath:
    path: /data/pv0001/
